name: CI

on: [ push, workflow_dispatch, pull_request_target ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run TESTS
        run: fastlane unit_test
      - name: Codecov
        uses: codecov/codecov-action@v1.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  #     - name: Upload Coverage Report
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: sq-generic.xml
  #         path: sq-generic.xml
  #         retention-days: 1

  # sonar_scan:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: Download Coverage Report
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: sq-generic.xml
  #         path: artifacts
  #     - name: Rename Paths in Coverage
  #       run:  sed 's+/Users/runner/work/Workflow/Workflow/++g' artifacts/sq-generic.xml > sq-generic.xml
  #     - name: SonarCloud Scan
  #       uses: sonarsource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # build_for_package_managers:
  #   needs: test
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Validate SwiftPM BUILDs
  #       run: fastlane build_swiftpm
  #     - name: Validate Cocoapods Can Deploy (lib lint)
  #       run: fastlane cocoapods_liblint
