# This workflow should run for PRs
# It should be safe and secure to do so.

name: Verify Pull Request
on: 
  pull_request:
    types: [opened, edited, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run TESTS
        run: fastlane unit_test
      - name: Codecov
        uses: codecov/codecov-action@v1.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
